### PR TITLE
Some issues

### PR DESCRIPTION
**Pull request by Klap-in**
Many most small changes.
Please see the separate commits.

### CODE REVIEW

**Comment by Klap-in** [comment]
A lot of different changes are included in this pull request.
I will continue in a new PR for additional set of changes. Review welcome.

**Comment by splitbrain** [comment]
I went through all commits. Looks awesome. Merging it.

**Comment by splitbrain** [comment]
Ahh I was too fast. 	03f4b01 caused a problem because there seems to be column missing:

    Column not found: 1054 Unknown column 'r1_.englishReadonly' in 'field list'

I think there should be a migration for that?

**Comment by Klap-in** [comment]
Symfony should perform the migration using the changed entity, it doesn't?

Some steps for performing an update are here mentioned: https://www.dokuwiki.org/teams:translate-tool#update Did you do something different?

I added another commit to master, which reverts a small change in a query function.

**Comment by splitbrain** [comment]
Hmm it said doctrine:schema:update should not be run in production. But it seems to have worked with --force anyway

**Pull request merged**
